name: Code Quality and Link Checks

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint CSS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Stylelint
        run: |
          npm install -g stylelint stylelint-config-standard

      - name: Lint CSS
        run: |
          stylelint "style.css"

  link_check:
    name: Check Broken Links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1
        with:
          args: --verbose --no-progress --exclude "https://rsergio.com" --exclude "https://www.linkedin.com" "**/*.html"
          fail: true